/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package encrypting_data;

import java.awt.*;

/**
 *
 * @author john
 */
public class PasswordCriteria extends javax.swing.JPanel {

    /**
     * Creates new form PasswordCriteria
     */
    public PasswordCriteria() {
        initComponents();
    }

    public void paintComponent(Graphics g){
        //Prompt some rules of password to the user
        super.paintComponent(g);
        Font f = new Font("",Font.BOLD,12);
        g.setFont(f);
        g.setColor(Color.BLACK);
        g.drawString("Notice:", 0, 20);
        Font f1 = new Font("",Font.PLAIN,11);
        g.setFont(f1);
        g.setColor(Color.BLACK);
        g.drawString("1. Your password should be no less than 6 and no longer than 16 characters long.", 0, 45);
        g.drawString("2. It should contain uppercase, lowercase letters, number and symbol.", 0, 70);
        g.drawString("3. It could contain space, but you can't use ';'.", 0, 95);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
